# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('step', models.SmallIntegerField()),
                ('unlock_dt', models.DateTimeField()),
                ('right_cnt', models.SmallIntegerField()),
                ('wrong_cnt', models.SmallIntegerField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('pronunciation', models.CharField(max_length=256)),
                ('meaning', models.CharField(max_length=256)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Book')),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.User'),
        ),
        migrations.AddField(
            model_name='memory',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Word'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.User'),
        ),
    ]
