# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_text',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_text',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='word_text',
        ),
    ]
