# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20160506_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word_text',
            new_name='word',
        ),
    ]
