# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20160506_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('w', 'Word to Meaning and Pronunciation'), ('m', 'Meaning to Word and Pronunciation')], max_length=1),
        ),
    ]
