# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20160506_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together=set([('user', 'word', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('book', 'word')]),
        ),
    ]
