# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20160507_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField()),
                ('right_cnt', models.IntegerField()),
                ('wrong_cnt', models.IntegerField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.User')),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('u', 'unknown'), ('w', 'wrong')], default='u', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together=set([('user', 'book', 'step')]),
        ),
    ]
