# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20160507_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='right_cnt',
            new_name='r_right_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='wrong_cnt',
            new_name='r_wrong_cnt',
        ),
        migrations.AddField(
            model_name='statistics',
            name='w_right_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='w_wrong_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='right_cnt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('u', 'Unknown'), ('r', 'Right'), ('w', 'Wrong')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='memory',
            name='step',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('w', 'Word'), ('m', 'Meaning')], max_length=1),
        ),
        migrations.AlterField(
            model_name='memory',
            name='unlock_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='wrong_cnt',
            field=models.SmallIntegerField(default=0),
        ),
    ]
