# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20160507_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='right_cnt',
            new_name='aware_cnt',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='wrong_cnt',
            new_name='forgot_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='r_right_cnt',
            new_name='a_aware_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='r_wrong_cnt',
            new_name='a_forgot_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='w_right_cnt',
            new_name='f_aware_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='w_wrong_cnt',
            new_name='f_forgot_cnt',
        ),
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[('u', 'Unknown'), ('a', 'Aware'), ('f', 'Forgot')], default='u', max_length=1),
        ),
    ]
