# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20160507_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='a_aware_cnt',
            new_name='aware_cnt',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='a_forgot_cnt',
            new_name='forgot_cnt',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='f_aware_cnt',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='f_forgot_cnt',
        ),
        migrations.AddField(
            model_name='statistics',
            name='status',
            field=models.CharField(choices=[('u', 'Unknown'), ('a', 'Aware'), ('f', 'Forgot')], default='u', max_length=1),
            preserve_default=False,
        ),
    ]
