# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20160507_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together=set([('user', 'book', 'step', 'status')]),
        ),
    ]
