# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20160507_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='group_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
