# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_memory_group_level'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([('user', 'book', 'type', 'unlock_dt'), ('user', 'book', 'type', 'create_dt')]),
        ),
        migrations.AlterIndexTogether(
            name='word',
            index_together=set([('book', 'create_dt')]),
        ),
    ]
