# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_auto_20160508_0119'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([]),
        ),
    ]
