# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_auto_20160508_0121'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([('user', 'book', 'type', 'create_dt'), ('user', 'book', 'type', 'unlock_dt')]),
        ),
    ]
