# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20160510_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(related_name='_word_related_+', to='exams.Word'),
        ),
    ]
