# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20160510_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='naver_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='antonym',
            field=models.ManyToManyField(blank=True, related_name='_word_antonym_+', to='exams.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_word_related_+', to='exams.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(blank=True, related_name='_word_synonym_+', to='exams.Word'),
        ),
    ]
