# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_auto_20160510_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='naver_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
