# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_auto_20160513_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Word'), ('m', 'Meaning')], max_length=1)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Book')),
            ],
        ),
        migrations.AlterField(
            model_name='memory',
            name='unlock_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Book'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='basket',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Memory'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.User'),
        ),
        migrations.AddField(
            model_name='basket',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Word'),
        ),
    ]
