# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_auto_20160701_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Memory', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set([('user', 'book', 'type', 'word')]),
        ),
    ]
