# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_auto_20160702_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Memory'),
        ),
    ]
