# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_auto_20160702_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_jp',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='word',
            name='example_kr',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
