# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_auto_20161016_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='skip_meaning',
            field=models.BooleanField(default=False),
        ),
    ]
