# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_word_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='trends',
            field=models.IntegerField(null=True),
        ),
    ]
