# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_word_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='random_step',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='trends',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
