# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0033_auto_20170110_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='random_step',
        ),
    ]
