# Generated by Django 2.0 on 2017-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('memo', models.CharField(max_length=64)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
