# Generated by Django 2.0 on 2017-12-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0002_auto_20171216_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swiss.League'),
            preserve_default=False,
        ),
    ]
