# Generated by Django 2.0 on 2017-12-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0004_auto_20171216_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches2', to='swiss.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
