# Generated by Django 2.0 on 2017-12-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0006_player_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
    ]
