# Generated by Django 2.0 on 2017-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0007_remove_player_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='memo',
            field=models.CharField(default='', max_length=64),
        ),
    ]
