# Generated by Django 2.0 on 2018-01-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('swiss', '0011_auto_20180105_1132'), ('swiss', '0012_auto_20180105_1134'), ('swiss', '0013_auto_20180105_1142'), ('swiss', '0014_league_user')]

    dependencies = [
        ('swiss', '0010_player_is_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=128)),
                ('expire_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['social_id'], name='social_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['access_token'], name='access_token_idx'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='social_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='access_token_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='league',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='swiss.User'),
            preserve_default=False,
        ),
    ]
